FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun install
RUN cd packages/db && bunx prisma generate && cd ../..
RUN DATABASE_URL="postgres://user:pass@localhost:5432/fakedb" bun run build

EXPOSE 3001 

CMD ["bun", "run", "start:web"] 