name: Deploy the backend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.backend
          push: true
          tags: satyanv/app:${{ github.sha }}

      - name: Deploy to VM
        run: |
          cat <<EOF > ~/ssh_key
${{ secrets.SSH_PRIVATE_KEY }}
EOF
          chmod 600 ~/ssh_key

          mkdir -p /home/runner/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > /home/runner/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.62.56.111 -t \
            "docker stop user_backend || true && docker rm user_backend || true && docker run --name user_backend -d -p 8080:8080 satyanv/app:${{ github.sha }}"
