name: Deploy the frontend
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4  # This is missing!
        
      - name: Docker login
        uses: docker/login-action@v3  # Fixed capitalization
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with: 
          context: .
          file: docker/Dockerfile.frontend
          build-args:
            - DATABASE_URL=${{ secrets.DATABASE_URL }}
          push: true
          tags: satyanv /app-frontend:${{ github.sha }}